from app.models.user import User
from app.models.movie import Movie
from app.models.review import Review
from app.models.favorite import Favorite
from app.models.search_history import SearchHistory
from app.models.notification import Notification
from app.models.watched import Watched
from app.models.watchlist import Watchlist
from app.models.user_preference import UserPreference